doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            cart_id: App\Cart\Infrastructure\Type\CartIdType
            cart_item_id: App\Cart\Infrastructure\Type\CartItemIdType
            cart_product_id: App\Cart\Infrastructure\Type\ProductIdType
            category_id: App\ProductManagement\Infrastructure\Persistence\Type\CategoryIdType
            currency: App\ProductManagement\Infrastructure\Persistence\Type\CurrencyType
            product_id: App\ProductManagement\Infrastructure\Persistence\Type\ProductIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App\ProductManagement\DomainModel:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/ProductManagement/Infrastructure/Persistence/Mapping'
                        prefix: 'App\ProductManagement\DomainModel'
                        alias: Product
                    App\Cart\DomainModel:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Cart/Infrastructure/Persistence/Mapping'
                        prefix: 'App\Cart\DomainModel'
                        alias: Cart
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
