version: '3.7'

services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app
        ports:
            - 3306

    php:
        build:
            context: .
            target: php
        volumes:
            - '.:/app'
        working_dir: /app
        depends_on:
            - database
